### ISSUE TITLE
array limited to 3 ALT

### ISSUE THREAD

**Issue by nickbrazeau** [mrc-ide/MIPanalyzer#1]
Hey Bob,

For the array under `mipanalyzer_data` your dimensions are dim(3, n, L) where 3 is ALT alleles, n is samples, L is loci. This absolutely makes sense for SNP data (where ALT is bounded by the 4 nucleotide bases) but will fail for INDEL data where the theoretical upper limit of ALT is n-1 (i.e. ever sample has its own unique INDEL). Granted, these latter points get a bit muddled, as we can see in example 5.1.2 [here](https://samtools.github.io/hts-specs/VCFv4.2.pdf).    
Regardless, I thought it was important to perserve the fact that ALT length changes depending on the loci in our data-structure. If you disagree and want to use an array of max(ALT) x n x L we can do that too?    
Also -- sorry if I missing something -- but it was unclear to me why coverage was an array? I just returned a simple matrix ?  

<img width="1731" alt="vcf_example_altref_indels" src="https://user-images.githubusercontent.com/12299990/49689329-9f345400-faed-11e8-8489-a12d13db8ef4.png">

*This is my vcf2mip_data function PR/proposa*: 

``` 
vcf2mipanalyzer_data <- function(file = NULL, vcfR = NULL, verbose = TRUE){
  #.....................
  # Read and check input
  #.....................
  if(is.null(file) & is.null(vcfR)){
    stop("You must specify an input: either a raw vcf file path or a vcfR object")
  } else if(!is.null(file) & !is.null(vcfR)){
    stop("You must specify one input: either a raw vcf file path or a vcfR object")

  } else if(!is.null(vcfR)){ # user specified a vcfR object
    if(!inherits(vcfR, "vcfR")){
      stop("vcfR object must be of class vcfR")
    }
    vcf <- vcfR

  } else if(!is.null(file)){ # user specified a file
    if(!file.exists(file)){
      stop("The vcf does not appear to exist at that file path")
    }
    vcf <- vcfR::read.vcfR(file=file, verbose=verbose) # read vcf
  }

  #..........................
  # find features and convert
  #..........................
  countmat <- vcfR::extract.gt(vcf, element="AD")
  counts <- sapply(1:nrow(countmat), function(x){ # R version of a for loop
    ret <- t(stringr::str_split(countmat[x,], ",", simplify = T))
    ret <- apply(ret, 2, as.numeric) # need to coerce to numeric here b/c of way vcfR extracts AD (can't set as.numeric T and retain all info) and to perserve df structure
    return(ret)
  }) # note, doing this way instead of an array to perserve the fact that the ALT count varies by loci as you could see by the command below
     # d <- sapply(vcf@fix[,5], function(x){ return(length(unlist(stringr::str_split(x, ","))))}) # ALT count per loci

  coverage <- vcfR::extract.gt(vcf, element="DP", as.numeric = T)

  # create data
  ret <- list(coverage = coverage,
              counts = counts,
              samples = colnames(vcf@gt)[2:ncol(vcf@gt)],
              loci = vcf@fix # keep all the info here not just loci pos?
              )

  # return in mipanalyzer_data class
  class(ret) <- "mipanalyzer_data"
  return(ret)
}

```

**Comment by nickbrazeau** [comment]
Also, it may be worthwhile to extract GT and potentially SQ from the format fields depending on Oz's final vcf format field?

**Comment by bobverity** [comment]
Hi Nick,

Thanks for this. You are absolutely right in terms of array dimensions, and yes coverage should be a matrix thanks. But an array with n-1 slices is going to be huge, and will undo any benefit of using this format. Can't really think of a good way around this, other than maybe use split format for different types? Any ideas?

Sent from my iPhone

On 8 Dec 2018, at 20:58, Nicholas Brazeau <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, it may be worthwhile to extract GT and potentially SQ from the format fields depending on Oz's final vcf format field?

**Comment by nickbrazeau** [comment]
Hey Bob,

Thanks for the reply! Although n-1 slices is possible, I think we will rarely -- if ever -- come close to this, as we typically mask out the really hypervariable regions in our variant calling/mip-design. So although I was being an alarmist, I think we should have a reasonable array. For example, in the Pf3K data, the maximum ALT count I saw was 6 for CHROM1, but I can happily go looking on others. 

Are you committed to an array of **d x n x L** size versus a list of matrices (L) of **d<sub>L</sub> x n** size, where d<sub>L</sub> is the max(ALT_count) for each loci, L ? I can see the advantage of the array in cpp... and if so, we can then just find the max(d<sub>L</sub>) and make an array of that "depth"?

**Comment by nickbrazeau** [comment]
Hey Bob, here is the updated function to handle biallelic and multiallelic. Depending on your preference for `test_that`, etc (per our email), I can finish and submit a PR. 


```


vcf2mipanalyzer_data <- function(file = NULL, vcfR = NULL, verbose = TRUE){
  #.....................
  # Read and check input
  #.....................
  if(is.null(file) & is.null(vcfR)){
    stop("You must specify an input: either a raw vcf file path or a vcfR object")
  } else if(!is.null(file) & !is.null(vcfR)){
    stop("You must specify one input: either a raw vcf file path or a vcfR object")

  } else if(!is.null(vcfR)){ # user specified a vcfR object
    if(!inherits(vcfR, "vcfR")){
      stop("vcfR object must be of class vcfR")
    }
    vcf <- vcfR

  } else if(!is.null(file)){ # user specified a file
    if(!file.exists(file)){
      stop("The vcf does not appear to exist at that file path")
    }
    vcf <- vcfR::read.vcfR(file=file, verbose=verbose) # read vcf
  }

  # sanity check to see if this is a normalized vcf or a long vcf
  # include in testthat vcf is not in long format?
  if(
    vcf@fix %>%
    tibble::as.tibble(.) %>%
    dplyr::group_by(CHROM, POS) %>%
    dplyr::summarise(locicount=n()) %>%
    dplyr::ungroup() %>%
    dplyr::summarise(maxlocicount = max(locicount)) != 1
  ){stop("This is not a normalized vcf. Some functions may behave differently. Check bcftools norm")}


  #.....................
  # code
  #.....................

  if(identical(vcf[vcfR::is.biallelic(vcf)], vcf)){ # if this is biallelic, store as ref count matrix and total depth
    countmat <- vcfR::extract.gt(vcf, element="AD")
    coverage <- vcfR::extract.gt(vcf, element="DP", as.numeric = T)

  }else{ # multiallelic, store as list
    countmat <- vcfR::extract.gt(vcf, element="AD")
    countlist <- split(countmat, seq(nrow(countmat)))
    counts <- parallel::mclapply(countlist, function(x){ # R version of a for loop
      ret <- t(stringr::str_split(x, ",", simplify = T))
      ret <- apply(ret, 2, as.numeric) # need to coerce to numeric here b/c of way vcfR extracts AD (can't set as.numeric T and retain all info) and to perserve df structure
      return(ret)
    }) # note, doing this way instead of an array to perserve the fact that the ALT count varies by loci as you could see by the command below
       # d <- sapply(vcf@fix[,5], function(x){ return(length(unlist(stringr::str_split(x, ","))))}) # ALT count per loci

    coverage <- vcfR::extract.gt(vcf, element="DP", as.numeric = T)
    coverage <- split(coverage, seq(nrow(coverage)))
  }

  # create data
  ret <- list(coverage = coverage,
              counts = counts,
              samples = colnames(vcf@gt)[2:ncol(vcf@gt)],
              loci = vcf@fix
              )

  # return in mipanalyzer_data class
  class(ret) <- "mipanalyzer_data"
  return(ret)
}

```
